image: node:slim

demos:
  stage: build

  before_script:
    - npm install

  script:
    - scripts/build

  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: push
    paths:
      - demos/public

pages:
  stage: deploy
  script:
    - mv demos/public ./public

  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: pull
    paths:
      - demos/public

  artifacts:
    paths:
      - public

  only:
    - master
